// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eiri/konyanko/ent/irregular"
)

// Irregular is the model entity for the Irregular schema.
type Irregular struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ViewURL holds the value of the "view_url" field.
	ViewURL string `json:"view_url,omitempty"`
	// DownloadURL holds the value of the "download_url" field.
	DownloadURL string `json:"download_url,omitempty"`
	// FileName holds the value of the "file_name" field.
	FileName string `json:"file_name,omitempty"`
	// FileSize holds the value of the "file_size" field.
	FileSize     int `json:"file_size,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Irregular) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case irregular.FieldID, irregular.FieldFileSize:
			values[i] = new(sql.NullInt64)
		case irregular.FieldViewURL, irregular.FieldDownloadURL, irregular.FieldFileName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Irregular fields.
func (i *Irregular) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case irregular.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		case irregular.FieldViewURL:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field view_url", values[j])
			} else if value.Valid {
				i.ViewURL = value.String
			}
		case irregular.FieldDownloadURL:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field download_url", values[j])
			} else if value.Valid {
				i.DownloadURL = value.String
			}
		case irregular.FieldFileName:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field file_name", values[j])
			} else if value.Valid {
				i.FileName = value.String
			}
		case irregular.FieldFileSize:
			if value, ok := values[j].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_size", values[j])
			} else if value.Valid {
				i.FileSize = int(value.Int64)
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Irregular.
// This includes values selected through modifiers, order, etc.
func (i *Irregular) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// Update returns a builder for updating this Irregular.
// Note that you need to call Irregular.Unwrap() before calling this method if this Irregular
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Irregular) Update() *IrregularUpdateOne {
	return NewIrregularClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Irregular entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Irregular) Unwrap() *Irregular {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Irregular is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Irregular) String() string {
	var builder strings.Builder
	builder.WriteString("Irregular(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("view_url=")
	builder.WriteString(i.ViewURL)
	builder.WriteString(", ")
	builder.WriteString("download_url=")
	builder.WriteString(i.DownloadURL)
	builder.WriteString(", ")
	builder.WriteString("file_name=")
	builder.WriteString(i.FileName)
	builder.WriteString(", ")
	builder.WriteString("file_size=")
	builder.WriteString(fmt.Sprintf("%v", i.FileSize))
	builder.WriteByte(')')
	return builder.String()
}

// Irregulars is a parsable slice of Irregular.
type Irregulars []*Irregular
