// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/eiri/konyanko/ent/releasegroup"
)

// ReleaseGroup is the model entity for the ReleaseGroup schema.
type ReleaseGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReleaseGroupQuery when eager-loading is set.
	Edges        ReleaseGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReleaseGroupEdges holds the relations/edges for other nodes in the graph.
type ReleaseGroupEdges struct {
	// Episodes holds the value of the episodes edge.
	Episodes []*Episode `json:"episodes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EpisodesOrErr returns the Episodes value or an error if the edge
// was not loaded in eager-loading.
func (e ReleaseGroupEdges) EpisodesOrErr() ([]*Episode, error) {
	if e.loadedTypes[0] {
		return e.Episodes, nil
	}
	return nil, &NotLoadedError{edge: "episodes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReleaseGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case releasegroup.FieldID:
			values[i] = new(sql.NullInt64)
		case releasegroup.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReleaseGroup fields.
func (rg *ReleaseGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case releasegroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rg.ID = int(value.Int64)
		case releasegroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				rg.Name = value.String
			}
		default:
			rg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReleaseGroup.
// This includes values selected through modifiers, order, etc.
func (rg *ReleaseGroup) Value(name string) (ent.Value, error) {
	return rg.selectValues.Get(name)
}

// QueryEpisodes queries the "episodes" edge of the ReleaseGroup entity.
func (rg *ReleaseGroup) QueryEpisodes() *EpisodeQuery {
	return NewReleaseGroupClient(rg.config).QueryEpisodes(rg)
}

// Update returns a builder for updating this ReleaseGroup.
// Note that you need to call ReleaseGroup.Unwrap() before calling this method if this ReleaseGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (rg *ReleaseGroup) Update() *ReleaseGroupUpdateOne {
	return NewReleaseGroupClient(rg.config).UpdateOne(rg)
}

// Unwrap unwraps the ReleaseGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rg *ReleaseGroup) Unwrap() *ReleaseGroup {
	_tx, ok := rg.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReleaseGroup is not a transactional entity")
	}
	rg.config.driver = _tx.drv
	return rg
}

// String implements the fmt.Stringer.
func (rg *ReleaseGroup) String() string {
	var builder strings.Builder
	builder.WriteString("ReleaseGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rg.ID))
	builder.WriteString("name=")
	builder.WriteString(rg.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ReleaseGroups is a parsable slice of ReleaseGroup.
type ReleaseGroups []*ReleaseGroup
