// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/eiri/konyanko/ent/episode"
	"github.com/eiri/konyanko/ent/irregular"
	"github.com/eiri/konyanko/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	episodeFields := schema.Episode{}.Fields()
	_ = episodeFields
	// episodeDescEpisodeNumber is the schema descriptor for episode_number field.
	episodeDescEpisodeNumber := episodeFields[0].Descriptor()
	// episode.DefaultEpisodeNumber holds the default value on creation for the episode_number field.
	episode.DefaultEpisodeNumber = episodeDescEpisodeNumber.Default.(int)
	// episode.EpisodeNumberValidator is a validator for the "episode_number" field. It is called by the builders before save.
	episode.EpisodeNumberValidator = episodeDescEpisodeNumber.Validators[0].(func(int) error)
	// episodeDescAnimeSeason is the schema descriptor for anime_season field.
	episodeDescAnimeSeason := episodeFields[1].Descriptor()
	// episode.DefaultAnimeSeason holds the default value on creation for the anime_season field.
	episode.DefaultAnimeSeason = episodeDescAnimeSeason.Default.(int)
	// episode.AnimeSeasonValidator is a validator for the "anime_season" field. It is called by the builders before save.
	episode.AnimeSeasonValidator = episodeDescAnimeSeason.Validators[0].(func(int) error)
	// episodeDescFileName is the schema descriptor for file_name field.
	episodeDescFileName := episodeFields[4].Descriptor()
	// episode.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	episode.FileNameValidator = episodeDescFileName.Validators[0].(func(string) error)
	// episodeDescFileSize is the schema descriptor for file_size field.
	episodeDescFileSize := episodeFields[5].Descriptor()
	// episode.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	episode.FileSizeValidator = episodeDescFileSize.Validators[0].(func(int) error)
	// episodeDescPublishDate is the schema descriptor for publish_date field.
	episodeDescPublishDate := episodeFields[9].Descriptor()
	// episode.DefaultPublishDate holds the default value on creation for the publish_date field.
	episode.DefaultPublishDate = episodeDescPublishDate.Default.(func() time.Time)
	irregularFields := schema.Irregular{}.Fields()
	_ = irregularFields
	// irregularDescFileName is the schema descriptor for file_name field.
	irregularDescFileName := irregularFields[2].Descriptor()
	// irregular.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	irregular.FileNameValidator = irregularDescFileName.Validators[0].(func(string) error)
	// irregularDescFileSize is the schema descriptor for file_size field.
	irregularDescFileSize := irregularFields[3].Descriptor()
	// irregular.FileSizeValidator is a validator for the "file_size" field. It is called by the builders before save.
	irregular.FileSizeValidator = irregularDescFileSize.Validators[0].(func(int) error)
	// irregularDescPublishDate is the schema descriptor for publish_date field.
	irregularDescPublishDate := irregularFields[4].Descriptor()
	// irregular.DefaultPublishDate holds the default value on creation for the publish_date field.
	irregular.DefaultPublishDate = irregularDescPublishDate.Default.(func() time.Time)
}
