// Code generated by ent, DO NOT EDIT.

package irregular

import (
	"entgo.io/ent/dialect/sql"
	"github.com/eiri/konyanko/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Irregular {
	return predicate.Irregular(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Irregular {
	return predicate.Irregular(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Irregular {
	return predicate.Irregular(sql.FieldLTE(FieldID, id))
}

// ViewURL applies equality check predicate on the "view_url" field. It's identical to ViewURLEQ.
func ViewURL(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldViewURL, v))
}

// DownloadURL applies equality check predicate on the "download_url" field. It's identical to DownloadURLEQ.
func DownloadURL(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldDownloadURL, v))
}

// FileName applies equality check predicate on the "file_name" field. It's identical to FileNameEQ.
func FileName(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldFileName, v))
}

// FileSize applies equality check predicate on the "file_size" field. It's identical to FileSizeEQ.
func FileSize(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldFileSize, v))
}

// ViewURLEQ applies the EQ predicate on the "view_url" field.
func ViewURLEQ(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldViewURL, v))
}

// ViewURLNEQ applies the NEQ predicate on the "view_url" field.
func ViewURLNEQ(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldNEQ(FieldViewURL, v))
}

// ViewURLIn applies the In predicate on the "view_url" field.
func ViewURLIn(vs ...string) predicate.Irregular {
	return predicate.Irregular(sql.FieldIn(FieldViewURL, vs...))
}

// ViewURLNotIn applies the NotIn predicate on the "view_url" field.
func ViewURLNotIn(vs ...string) predicate.Irregular {
	return predicate.Irregular(sql.FieldNotIn(FieldViewURL, vs...))
}

// ViewURLGT applies the GT predicate on the "view_url" field.
func ViewURLGT(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldGT(FieldViewURL, v))
}

// ViewURLGTE applies the GTE predicate on the "view_url" field.
func ViewURLGTE(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldGTE(FieldViewURL, v))
}

// ViewURLLT applies the LT predicate on the "view_url" field.
func ViewURLLT(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldLT(FieldViewURL, v))
}

// ViewURLLTE applies the LTE predicate on the "view_url" field.
func ViewURLLTE(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldLTE(FieldViewURL, v))
}

// ViewURLContains applies the Contains predicate on the "view_url" field.
func ViewURLContains(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldContains(FieldViewURL, v))
}

// ViewURLHasPrefix applies the HasPrefix predicate on the "view_url" field.
func ViewURLHasPrefix(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldHasPrefix(FieldViewURL, v))
}

// ViewURLHasSuffix applies the HasSuffix predicate on the "view_url" field.
func ViewURLHasSuffix(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldHasSuffix(FieldViewURL, v))
}

// ViewURLEqualFold applies the EqualFold predicate on the "view_url" field.
func ViewURLEqualFold(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEqualFold(FieldViewURL, v))
}

// ViewURLContainsFold applies the ContainsFold predicate on the "view_url" field.
func ViewURLContainsFold(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldContainsFold(FieldViewURL, v))
}

// DownloadURLEQ applies the EQ predicate on the "download_url" field.
func DownloadURLEQ(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldDownloadURL, v))
}

// DownloadURLNEQ applies the NEQ predicate on the "download_url" field.
func DownloadURLNEQ(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldNEQ(FieldDownloadURL, v))
}

// DownloadURLIn applies the In predicate on the "download_url" field.
func DownloadURLIn(vs ...string) predicate.Irregular {
	return predicate.Irregular(sql.FieldIn(FieldDownloadURL, vs...))
}

// DownloadURLNotIn applies the NotIn predicate on the "download_url" field.
func DownloadURLNotIn(vs ...string) predicate.Irregular {
	return predicate.Irregular(sql.FieldNotIn(FieldDownloadURL, vs...))
}

// DownloadURLGT applies the GT predicate on the "download_url" field.
func DownloadURLGT(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldGT(FieldDownloadURL, v))
}

// DownloadURLGTE applies the GTE predicate on the "download_url" field.
func DownloadURLGTE(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldGTE(FieldDownloadURL, v))
}

// DownloadURLLT applies the LT predicate on the "download_url" field.
func DownloadURLLT(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldLT(FieldDownloadURL, v))
}

// DownloadURLLTE applies the LTE predicate on the "download_url" field.
func DownloadURLLTE(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldLTE(FieldDownloadURL, v))
}

// DownloadURLContains applies the Contains predicate on the "download_url" field.
func DownloadURLContains(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldContains(FieldDownloadURL, v))
}

// DownloadURLHasPrefix applies the HasPrefix predicate on the "download_url" field.
func DownloadURLHasPrefix(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldHasPrefix(FieldDownloadURL, v))
}

// DownloadURLHasSuffix applies the HasSuffix predicate on the "download_url" field.
func DownloadURLHasSuffix(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldHasSuffix(FieldDownloadURL, v))
}

// DownloadURLEqualFold applies the EqualFold predicate on the "download_url" field.
func DownloadURLEqualFold(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEqualFold(FieldDownloadURL, v))
}

// DownloadURLContainsFold applies the ContainsFold predicate on the "download_url" field.
func DownloadURLContainsFold(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldContainsFold(FieldDownloadURL, v))
}

// FileNameEQ applies the EQ predicate on the "file_name" field.
func FileNameEQ(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldFileName, v))
}

// FileNameNEQ applies the NEQ predicate on the "file_name" field.
func FileNameNEQ(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldNEQ(FieldFileName, v))
}

// FileNameIn applies the In predicate on the "file_name" field.
func FileNameIn(vs ...string) predicate.Irregular {
	return predicate.Irregular(sql.FieldIn(FieldFileName, vs...))
}

// FileNameNotIn applies the NotIn predicate on the "file_name" field.
func FileNameNotIn(vs ...string) predicate.Irregular {
	return predicate.Irregular(sql.FieldNotIn(FieldFileName, vs...))
}

// FileNameGT applies the GT predicate on the "file_name" field.
func FileNameGT(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldGT(FieldFileName, v))
}

// FileNameGTE applies the GTE predicate on the "file_name" field.
func FileNameGTE(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldGTE(FieldFileName, v))
}

// FileNameLT applies the LT predicate on the "file_name" field.
func FileNameLT(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldLT(FieldFileName, v))
}

// FileNameLTE applies the LTE predicate on the "file_name" field.
func FileNameLTE(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldLTE(FieldFileName, v))
}

// FileNameContains applies the Contains predicate on the "file_name" field.
func FileNameContains(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldContains(FieldFileName, v))
}

// FileNameHasPrefix applies the HasPrefix predicate on the "file_name" field.
func FileNameHasPrefix(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldHasPrefix(FieldFileName, v))
}

// FileNameHasSuffix applies the HasSuffix predicate on the "file_name" field.
func FileNameHasSuffix(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldHasSuffix(FieldFileName, v))
}

// FileNameEqualFold applies the EqualFold predicate on the "file_name" field.
func FileNameEqualFold(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldEqualFold(FieldFileName, v))
}

// FileNameContainsFold applies the ContainsFold predicate on the "file_name" field.
func FileNameContainsFold(v string) predicate.Irregular {
	return predicate.Irregular(sql.FieldContainsFold(FieldFileName, v))
}

// FileSizeEQ applies the EQ predicate on the "file_size" field.
func FileSizeEQ(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldEQ(FieldFileSize, v))
}

// FileSizeNEQ applies the NEQ predicate on the "file_size" field.
func FileSizeNEQ(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldNEQ(FieldFileSize, v))
}

// FileSizeIn applies the In predicate on the "file_size" field.
func FileSizeIn(vs ...int) predicate.Irregular {
	return predicate.Irregular(sql.FieldIn(FieldFileSize, vs...))
}

// FileSizeNotIn applies the NotIn predicate on the "file_size" field.
func FileSizeNotIn(vs ...int) predicate.Irregular {
	return predicate.Irregular(sql.FieldNotIn(FieldFileSize, vs...))
}

// FileSizeGT applies the GT predicate on the "file_size" field.
func FileSizeGT(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldGT(FieldFileSize, v))
}

// FileSizeGTE applies the GTE predicate on the "file_size" field.
func FileSizeGTE(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldGTE(FieldFileSize, v))
}

// FileSizeLT applies the LT predicate on the "file_size" field.
func FileSizeLT(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldLT(FieldFileSize, v))
}

// FileSizeLTE applies the LTE predicate on the "file_size" field.
func FileSizeLTE(v int) predicate.Irregular {
	return predicate.Irregular(sql.FieldLTE(FieldFileSize, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Irregular) predicate.Irregular {
	return predicate.Irregular(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Irregular) predicate.Irregular {
	return predicate.Irregular(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Irregular) predicate.Irregular {
	return predicate.Irregular(sql.NotPredicates(p))
}
